"""
Django settings for pybarsys project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__ + "/..")))

# Constance settings
CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'bootstrap3',
    'barsys.apps.BarsysConfig',
    'constance',
    'constance.backends.database',
    'django_filters',
    'crispy_forms',
]

STATIC_URL = '/static/'

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'pybarsys.urls'
LOGIN_REDIRECT_URL = 'user_home'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pybarsys.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

AUTH_USER_MODEL = 'barsys.User'  # custom Barsys user model

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
from decimal import Decimal

# Constance settings
CONSTANCE_CONFIG = {
    'NUM_USER_PURCHASE_HISTORY': (15, "Number of purchases to show on user history page"),
    'SUM_COST_USER_PURCHASE_HISTORY': (True, "Whether to show total cost of unbilled purchases on user history page"),
    'NUM_MAIN_LAST_PURCHASES': (5, "Number of purchases to show on main page"),

    'MAIL_INVOICE_SUBJECT': ('Invoice from Barsys bar', 'Subject of an invoice mail'),
    'MAIL_PURCHASE_NOTIFICATION_SUBJECT': ('Purchase notification from Barsys bar', 'Subject of a purchase notification to dependants'),
    'MAIL_PAYMENT_REMINDER_SUBJECT': ('Payment reminder from Barsys bar', 'Subject of a payment reminder mail'),
    'MAIL_NAME_OF_BAR': ('Barsys bar', 'Name of the bar'),
    'MAIL_CONTACT_EMAIL': ('bar@example.com', 'Bar contact email address'),
    'MAIL_BANK_DETAILS': ('Bank account No. 55542\n'
                          'Routing No. 2718\n'
                          'Royal Bank of Moldova', 'Bank account details'),
    'MAIL_BALANCE_SEND_MONEY': (Decimal('0'), 'Below this account balance the user should send money.'),

}

CONSTANCE_CONFIG_FIELDSETS = {
    'Main page': ('NUM_USER_PURCHASE_HISTORY', 'SUM_COST_USER_PURCHASE_HISTORY', 'NUM_MAIN_LAST_PURCHASES',),
    'Mail': ('MAIL_INVOICE_SUBJECT', 'MAIL_NAME_OF_BAR', 'MAIL_CONTACT_EMAIL', 'MAIL_BANK_DETAILS',
             'MAIL_BALANCE_SEND_MONEY', 'MAIL_PAYMENT_REMINDER_SUBJECT'),
}

CRISPY_TEMPLATE_PACK = 'bootstrap3'

BOOTSTRAP3 = {
    # The URL to the jQuery JavaScript file
    'jquery_url': '/static/barsys/jquery/jquery.min.js',

    # The Bootstrap base URL
    'base_url': '/static/barsys/bootstrap-3.3.7-dist/',

    # The complete URL to the Bootstrap CSS file (None means no theme)
    'theme_url': '/static/barsys/bootstrap-3.3.7-dist/css/bootstrap-theme.css',

}
