# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0002_auto_20170403_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
