# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0007_statsdisplay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statsdisplay',
            name='sort_by_number_of_purchases',
        ),
        migrations.RemoveField(
            model_name='statsdisplay',
            name='sort_by_total_cost',
        ),
        migrations.AddField(
            model_name='statsdisplay',
            name='sort_by_and_show',
            field=models.CharField(choices=[('NP', 'Sort by and show number of purchases'), ('TC', 'Sort by total cost')], default='NP', max_length=2),
        ),
        migrations.AlterField(
            model_name='statsdisplay',
            name='filter_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barsys.Category'),
        ),
        migrations.AlterField(
            model_name='statsdisplay',
            name='filter_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barsys.Product'),
        ),
    ]
