# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0009_statsdisplay_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='statsdisplay',
            name='row_string',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='statsdisplay',
            name='filter_category',
            field=models.ForeignKey(blank=True, help_text='If none, any category is used', null=True, on_delete=django.db.models.deletion.SET_NULL, to='barsys.Category'),
        ),
        migrations.AlterField(
            model_name='statsdisplay',
            name='filter_product',
            field=models.ForeignKey(blank=True, help_text='If none, any product is used', null=True, on_delete=django.db.models.deletion.SET_NULL, to='barsys.Product'),
        ),
        migrations.AlterField(
            model_name='statsdisplay',
            name='show_by_default',
            field=models.BooleanField(help_text='Whether this should always be shown first. If not, it can be selected by cycling through the other ones, as long as any one is shown by default.'),
        ),
    ]
