# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0010_auto_20170405_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsdisplay',
            name='row_string',
            field=models.CharField(blank=True, help_text="This is shown on the right side of each stats row in the format '[row_string] [user_name]', so one example row could be '10x Coffee by Peter' with 'Coffee by' being the ROW_STRING", max_length=15),
        ),
        migrations.AlterField(
            model_name='statsdisplay',
            name='sort_by_and_show',
            field=models.CharField(choices=[('NP', 'Sort by and show number of purchases'), ('TCR', 'Sort by total cost and show rank'), ('TCC', 'Sort by total cost and show cost')], default='NP', max_length=3),
        ),
    ]
