# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0011_auto_20170406_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsdisplay',
            name='sort_by_and_show',
            field=models.CharField(choices=[('NP', 'Sort by and show number of purchases'), ('TC', 'Sort by total cost and show rank')], default='NP', max_length=2),
        ),
    ]
