# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0013_auto_20170406_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category__name', 'name', 'amount']},
        ),
        migrations.AddField(
            model_name='user',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
