# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 11:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0014_auto_20170406_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='statsdisplay',
            name='time_period',
            field=models.DurationField(default=datetime.timedelta(7), help_text='Duration over which statistics are to be evaluated'),
        ),
    ]
