# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 16:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0015_statsdisplay_time_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Multiple products can have the same name as long as the amount is different', max_length=40),
        ),
        migrations.AlterField(
            model_name='statsdisplay',
            name='time_period',
            field=models.DurationField(default=datetime.timedelta(7), help_text="Duration over which statistics are to be evaluated in the format 'WEEKS HOURS:MINUTES:SECONDS'"),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='User account is activated'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='User may login as admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_buyer',
            field=models.BooleanField(default=True, help_text='User may buy products'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='User is shown under favorites'),
        ),
        migrations.AlterField(
            model_name='user',
            name='purchases_paid_by',
            field=models.ForeignKey(blank=True, default=None, help_text='Someone else is responsible to pay for all purchases made by this user. Invoices are sent to the responsible person and a copy is sent to the user itself as a notification.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
