# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 16:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0021_auto_20170409_0023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='statsdisplay',
            options={'ordering': ['-show_by_default', 'title']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['display_name']},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='purchases_paid_by',
            new_name='purchases_paid_by_other',
        ),
        migrations.AlterField(
            model_name='statsdisplay',
            name='time_period',
            field=models.DurationField(default=datetime.timedelta(7), help_text="Duration over which statistics are to be evaluated in the format 'DAYS HOURS:MINUTES:SECONDS'"),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(help_text='What is shown on the main purchase page', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Email is used as username when logging into the user-only area', max_length=255, unique=True),
        ),
    ]
