# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 15:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0026_auto_20170410_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='comment',
            field=models.CharField(blank=True, help_text='An optional comment for this purchase', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Positive amounts are deposits by the user. Negative amounts are payouts to the user.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='purchases_paid_by_other',
            field=models.ForeignKey(blank=True, default=None, help_text='Another active user (who pays for their own purchases) is responsible to pay for all purchases made by this user. Invoices are sent to the responsible user, and a copy goes to the dependent as notification.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
