# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0027_auto_20170417_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductChangeAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('products', models.ManyToManyField(to='barsys.Product')),
            ],
        ),
    ]
