# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0030_auto_20170417_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='productchangeaction',
            name='toggle_active',
            field=models.BooleanField(default=False, help_text='Toggle active state of products'),
        ),
    ]
