# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0031_productchangeaction_toggle_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productchangeaction',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
