# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0033_auto_20170417_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_bold',
            field=models.BooleanField(default=False, help_text='Whether this product is shown bold on the purchasing page'),
        ),
    ]
