# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0034_product_is_bold'),
    ]

    operations = [
        migrations.AddField(
            model_name='productchangeaction',
            name='toggle_bold',
            field=models.BooleanField(default=False, help_text='Toggle bold state of products'),
        ),
    ]
