# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 18:33
from __future__ import unicode_literals

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0035_productchangeaction_toggle_bold'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAutochange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='If set, will change the price to this value', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
        ),
        migrations.CreateModel(
            name='ProductAutochangeSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('products', models.ManyToManyField(help_text='These products will be changed.', through='barsys.ProductAutochange', to='barsys.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='productchangeaction',
            name='products',
        ),
        migrations.DeleteModel(
            name='PurchaseSummary',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='statsdisplay',
            name='show_by_default',
            field=models.BooleanField(default=False, help_text='Whether this should always be shown first. If not, it can be selected by cycling through the other ones, as long as any one is shown by default.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='purchases_paid_by_other',
            field=models.ForeignKey(blank=True, default=None, help_text='If set, another active user (who pays for their own purchases) is responsible to pay for all purchases made by this user. Invoices are sent to the responsible user, and a copy goes to the dependent as notification.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ProductChangeAction',
        ),
        migrations.AddField(
            model_name='productautochange',
            name='pc_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barsys.ProductAutochangeSet'),
        ),
        migrations.AddField(
            model_name='productautochange',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barsys.Product'),
        ),
    ]
