# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0036_auto_20170421_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='productautochangeset',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
