# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0037_productautochangeset_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productautochange',
            old_name='price',
            new_name='set_price',
        ),
        migrations.AddField(
            model_name='productautochange',
            name='change_active',
            field=models.CharField(choices=[('NC', 'No change'), ('YES', 'Change to yes'), ('NO', 'Change to no')], default='NC', max_length=3),
        ),
        migrations.AddField(
            model_name='productautochange',
            name='change_bold',
            field=models.CharField(choices=[('NC', 'No change'), ('YES', 'Change to yes'), ('NO', 'Change to no')], default='NC', max_length=3),
        ),
    ]
