# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 13:12
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0038_auto_20170421_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='statsdisplay',
            name='time_period_method',
            field=models.CharField(choices=[('FIXED', 'Fixed duration'), ('MONDAY', 'Since midnight of last monday'), ('1st', 'Since 1st of current month'), ('JAN_1st', 'Since January 1st of current year')], default='MONDAY', max_length=7),
        ),
        migrations.AlterField(
            model_name='statsdisplay',
            name='time_period',
            field=models.DurationField(default=datetime.timedelta(7), help_text="Duration over which statistics are to be evaluated in the format 'DAYS HOURS:MINUTES:SECONDS'. Only used if time period method is 'fixed duration'"),
        ),
    ]
