# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0039_auto_20170423_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsdisplay',
            name='time_period_method',
            field=models.CharField(choices=[('FIXED', 'Fixed duration'), ('MONDAY', 'Since Monday of current week (midnight)'), ('1st', 'Since 1st of current month (midnight)'), ('JAN_1st', 'Since January 1st of current year (midnight)')], default='MONDAY', help_text='Method of how to determine the time frame in which purchases count into this statistics display.', max_length=7),
        ),
    ]
