# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0040_auto_20170424_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statsdisplay',
            name='filter_category',
        ),
        migrations.RemoveField(
            model_name='statsdisplay',
            name='filter_product',
        ),
        migrations.AddField(
            model_name='statsdisplay',
            name='filter_by_category',
            field=models.ManyToManyField(blank=True, help_text='If none, all categories are used', to='barsys.Category'),
        ),
        migrations.AddField(
            model_name='statsdisplay',
            name='filter_by_product',
            field=models.ManyToManyField(blank=True, help_text='If none, all products are used', to='barsys.Product'),
        ),
        migrations.AlterField(
            model_name='statsdisplay',
            name='row_string',
            field=models.CharField(blank=True, help_text="This is shown on the right side of each stats row in the format '[row_string] [user_name]', so one example row could be '10x Coffee by Peter' with 'Coffee by' being the row_string", max_length=15),
        ),
    ]
