# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0041_auto_20170424_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsdisplay',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
