# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 10:19
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0042_auto_20170424_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leftover_quantity', models.PositiveIntegerField(help_text='How many items can still be purchased for free')),
                ('comment', models.CharField(blank=True, max_length=50)),
                ('purchasable', models.BooleanField(default=True, help_text='Whether these free items are shown on the main page and automatically used (i.e. purchase has no cost) when a user buys the product. If no, only admins can change the leftover quantity.')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('giver', models.ForeignKey(blank=True, help_text='User thanks to whom this product is free', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barsys.Product')),
            ],
        ),
    ]
