# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 07:55
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0043_freeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='free_item',
            field=models.ForeignKey(blank=True, help_text='If this purchase was free, this is set to the used free item', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='barsys.FreeItem'),
        ),
    ]
