# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0044_purchase_free_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freeitem',
            options={'ordering': ['-leftover_quantity']},
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='free_item',
        ),
        migrations.AddField(
            model_name='purchase',
            name='free_item_description',
            field=models.CharField(blank=True, help_text='Description of free item (only if this was purchased for free)', max_length=120),
        ),
    ]
