# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0046_auto_20170426_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_free_item_purchase',
            field=models.BooleanField(default=False, help_text='Whether this purchase was done with a free item (i.e. it was shown as free on the main page)'),
        ),
    ]
