# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0047_purchase_is_free_item_purchase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category__name', '-is_bold', 'name']},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.CharField(max_length=12),
        ),
    ]
