# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-05 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('barsys', '0049_auto_20170801_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productautochangeset',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='statsdisplay',
            name='time_period_method',
            field=models.CharField(
                choices=[('FIXED', 'Fixed duration'), ('MONDAY', 'Since Monday of current week (midnight)'),
                         ('1st', 'Since 1st of current month (midnight)'),
                         ('JAN_1st', 'Since January 1st of current year (midnight)'),
                         ('TOD_MID', 'Since midnight (00:00) of current day'),
                         ('4pm', 'Since last time it was 4pm (16:00)')], default='MONDAY',
                help_text='Method of how to determine the time frame in which purchases count into this statistics display.',
                max_length=7),
        ),
    ]
