# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-23 13:38
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


def set_value_dates(apps, schema_editor):
    # Set value_date to created_date of already existing payments
    Payment = apps.get_model("barsys", "Payment")
    for payment in Payment.objects.all():
        payment.value_date = payment.created_date
        payment.save()


class Migration(migrations.Migration):
    dependencies = [
        ('barsys', '0050_auto_20170805_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='value_date',
            field=models.DateField(default=datetime.date.today, help_text="Date when payment is considered effective "
                                                                          "(only for display)"),
        ),
        migrations.RunPython(set_value_dates),
    ]
