# Generated by Django 2.0.1 on 2018-01-18 15:00

import django.db.models.query_utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('barsys', '0051_payment_value_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeitem',
            name='giver',
            field=models.ForeignKey(blank=True, help_text='User thanks to whom this product is free', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='purchases_paid_by_other',
            field=models.ForeignKey(blank=True, default=None,
                                    help_text='If set, another active user (who pays for their own purchases) is responsible to pay for all purchases made by this user. Invoices are sent to the responsible user, and a copy goes to the dependent as notification.',
                                    limit_choices_to=django.db.models.query_utils.Q(purchases_paid_by_other=None),
                                    null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
