# Generated by Django 2.0.1 on 2018-02-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('barsys', '0052_auto_20180118_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2,
                                      help_text='Positive amounts are deposits by the user. Negative amounts are payouts to the user.',
                                      max_digits=6),
        ),
    ]
