# Generated by Django 2.0.1 on 2018-03-04 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('barsys', '0053_auto_20180209_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='amount',
            new_name='amount_purchases',
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_payments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='barsys.Invoice'),
        ),
    ]
