# Generated by Django 2.0.1 on 2018-03-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('barsys', '0055_create_invoices_for_all_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='productautochangeset',
            name='change_others_active',
            field=models.CharField(choices=[('NC', 'No change'), ('YES', 'Change to yes'), ('NO', 'Change to no')],
                                   default='NC', help_text='Change active state of other products', max_length=3),
        ),
        migrations.AddField(
            model_name='productautochangeset',
            name='change_others_bold',
            field=models.CharField(choices=[('NC', 'No change'), ('YES', 'Change to yes'), ('NO', 'Change to no')],
                                   default='NC', help_text='Change bold state of other products', max_length=3),
        ),
    ]
