# Generated by Django 2.0.3 on 2018-10-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('barsys', '0057_user_is_autolocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_autolocked',
            field=models.BooleanField(default=False,
                                      help_text='User was automatically locked due to the outstanding balance'),
        ),
    ]
