# Generated by Django 2.2.16 on 2020-10-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0058_auto_20181003_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
