# Generated by Django 2.2.28 on 2026-05-15 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0059_invoice_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
