# Generated by Django 2.2.28 on 2026-04-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0060_auto_20260515_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='easyverein_contact_details_url',
            field=models.URLField(blank=True, help_text='URL of the linked EasyVerein contact-details resource', null=True),
        ),
    ]
