# Generated by Django 5.2.15 on 2026-06-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0063_site_settings_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_virtual_payment',
            field=models.BooleanField(default=False, help_text='Automatically created payments (e.g. by EasyVerein invoicing) that should be deleted together with their invoice.'),
        ),
    ]
