# Generated by Django 5.2.15 on 2026-06-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0064_payment_is_virtual_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='easyverein_finalize_invoices',
            field=models.BooleanField(default=False, help_text='If enabled, invoices are finalized (draft state removed, PDF generated). If disabled, they are kept as drafts. Note: does not send email to members.'),
        ),
    ]
