# Generated by Django 5.2.15 on 2026-06-07 13:54

from django.db import migrations


def blank_urls_to_null(apps, schema_editor):
    # Normalize "" to NULL so unlinked users do not collide under the upcoming
    # unique constraint on easyverein_contact_details_url.
    User = apps.get_model("barsys", "User")
    User.objects.filter(easyverein_contact_details_url="").update(
        easyverein_contact_details_url=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0065_sitesettings_easyverein_finalize_invoices'),
    ]

    operations = [
        migrations.RunPython(blank_urls_to_null, migrations.RunPython.noop),
    ]
