# Generated by Django 5.2.15 on 2026-06-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsys', '0066_normalize_blank_easyverein_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='easyverein_contact_details_url',
            field=models.URLField(blank=True, help_text='URL of the linked EasyVerein contact-details resource', null=True, unique=True),
        ),
    ]
